# Generated by Django 4.2.2 on 2023-06-22 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ad')),
                ('description', models.TextField(verbose_name='tesvir')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='qiymet')),
                ('price_currency', models.CharField(choices=[('AZN', 'AZN'), ('USD', 'USD'), ('EUR', 'EUR')], default='AZN', max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ManyToManyField(related_name='products', to='product.category')),
            ],
            options={
                'verbose_name': 'Mehsul',
                'verbose_name_plural': 'Mehsullar',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products', verbose_name='shekil')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'verbose_name': 'Mehsul shekili',
                'verbose_name_plural': 'Mehsullar shekilleri',
            },
        ),
    ]
