# Generated by Django 4.2.2 on 2023-06-22 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Mehsul shekili', 'verbose_name_plural': 'Mehsullarin shekilleri'},
        ),
    ]
