# Generated by Django 4.2.2 on 2023-06-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Yazar', 'verbose_name_plural': 'Yazarlar'},
        ),
    ]
