# Generated by Django 4.2.2 on 2023-06-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloq', '0003_category_bloq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloq',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
