# Generated by Django 4.2.2 on 2023-06-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloq', '0004_alter_bloq_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kateqoriya', 'verbose_name_plural': 'Kateqoriyalar'},
        ),
    ]
