# Generated by Django 4.2.2 on 2023-08-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainorder',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
