# Generated by Django 4.2.2 on 2023-06-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Haqqimizda')),
                ('description', models.TextField(verbose_name='Haqqimizda')),
                ('image', models.ImageField(upload_to='about')),
            ],
            options={
                'verbose_name': 'Haqqimizda',
                'verbose_name_plural': 'Haqqimizda',
            },
        ),
    ]
