# Generated by Django 4.2.2 on 2023-06-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=2000, verbose_name='Adres')),
            ],
            options={
                'verbose_name': 'Unvan',
                'verbose_name_plural': 'Unvanlar',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.TextField(max_length=2000, verbose_name='Elektron pocht')),
            ],
            options={
                'verbose_name': 'Elektron unvan',
                'verbose_name_plural': 'Elektron unvan',
            },
        ),
        migrations.CreateModel(
            name='OpenTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=2000, verbose_name='Rejim')),
                ('open', models.TextField(max_length=2000, verbose_name='Ish rejimi')),
            ],
            options={
                'verbose_name': 'Rejim',
                'verbose_name_plural': 'Rejim',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Telefon')),
                ('phone', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Telefon',
                'verbose_name_plural': 'Telefonlar',
            },
        ),
    ]
