# Generated by Django 4.2.2 on 2023-06-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='name',
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Telefon'),
        ),
    ]
