# Generated by Django 4.2.2 on 2023-07-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_phone_name_alter_phone_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('address', models.TextField(max_length=2000, verbose_name='Unvan')),
                ('mail', models.TextField(max_length=2000, verbose_name='Elektron pocht')),
                ('open', models.TextField(max_length=2000, verbose_name='Ish rejimi')),
            ],
            options={
                'verbose_name': 'Elaqe',
                'verbose_name_plural': 'Elaqe',
            },
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='OpenTime',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
