# Generated by Django 4.2.2 on 2023-08-31 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
