# Generated by Django 4.2.2 on 2023-09-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_message_email_alter_message_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'message', 'verbose_name_plural': 'message'},
        ),
    ]
