# Generated by Django 4.2.2 on 2023-07-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'hesab', 'verbose_name_plural': 'hesablar'},
        ),
    ]
